### ISSUE TITLE
License missing, not able to replicate

### ISSUE THREAD

**Issue by mvalsells** [sikozonpc/ecom#1]
There is no license document in the repository, can the code or parts of it be used by others?

From [Licensing a repository - Github](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license)

"You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that **you retain all rights to your source code and no one may reproduce**, distribute, or create derivative works from your work."

Right now no one has de right to replicate your code, including trying to learn from the [youtube video](https://www.youtube.com/watch?v=7VLmLOiQ3ck)

**Comment by sikozonpc** [comment]
@mvalsells Thank you for pointing that out, I had no idea that was the default.
I would not worry too much about it but I've updated it with a license nonetheless.

Thanks for sharing!
